using System;
using System.Collections.Generic;

namespace Atsolution.Efs.Entities
{
    public partial class CareceiptPaymentList
    {
        public string RefId { get; set; }
        public DateTime? CabarefDate { get; set; }
        public DateTime? CarefDate { get; set; }
        public DateTime? RefDate { get; set; }
        public DateTime? CabapostedDate { get; set; }
        public DateTime? CapostedDate { get; set; }
        public DateTime? PostedDate { get; set; }
        public int? Reftype { get; set; }
        public string RefNoFinance { get; set; }
        public string RefNoManagement { get; set; }
        public string CabarefNoManagement { get; set; }
        public string CarefNoFinance { get; set; }
        public bool? IsValueDecrementFromStock { get; set; }
        public string CabarefNoFinance { get; set; }
        public string CarefNoManagement { get; set; }
        public bool? IsFreightService { get; set; }
        public bool? IsPostedFinance { get; set; }
        public bool? IsPostedManagement { get; set; }
        public int? ReasonTypeId { get; set; }
        public int? IncludeInvoice { get; set; }
        public string SainvoiceRefId { get; set; }
        public string PuinvoiceRefId { get; set; }
        public string AccountObjectId { get; set; }
        public string AccountObjectName { get; set; }
        public string AccountObjectAddress { get; set; }
        public string ReceiverAddress { get; set; }
        public string AccountObjectBankAccount { get; set; }
        public string AccountObjectBankName { get; set; }
        public string BranchId { get; set; }
        public string OutDocumentIncluded { get; set; }
        public string AccountObjectContactName { get; set; }
        public string Payer { get; set; }
        public string SupplierId { get; set; }
        public string IdentificationNumber { get; set; }
        public string PayerAddress { get; set; }
        public string SupplierName { get; set; }
        public bool? IsOutwardExported { get; set; }
        public DateTime? IssueDate { get; set; }
        public string PayReason { get; set; }
        public string CadocumentIncluded { get; set; }
        public string IssueBy { get; set; }
        public int? DueDay { get; set; }
        public bool? IsInvoiceExported { get; set; }
        public string Receiver { get; set; }
        public DateTime? DueDate { get; set; }
        public string JournalMemo { get; set; }
        public string DocumentIncluded { get; set; }
        public string EmployeeId { get; set; }
        public string CabajournalMemo { get; set; }
        public decimal? TotalSaleAmountOc { get; set; }
        public string CabadocumentIncluded { get; set; }
        public decimal? TotalSaleAmount { get; set; }
        public string BankAccountId { get; set; }
        public string BankName { get; set; }
        public string PaymentTermId { get; set; }
        public int? DueTime { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public decimal? TotalExportTaxAmountOc { get; set; }
        public decimal? TotalAmountOc { get; set; }
        public decimal? TotalExportTaxAmount { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? TotalImportTaxAmountOc { get; set; }
        public decimal? TotalImportTaxAmount { get; set; }
        public int? DebtStatus { get; set; }
        public decimal? TotalVatamountOc { get; set; }
        public decimal? TotalVatamount { get; set; }
        public decimal? TotalDiscountAmountOc { get; set; }
        public decimal? TotalDiscountAmount { get; set; }
        public decimal? TotalFreightAmount { get; set; }
        public decimal? TotalInwardAmount { get; set; }
        public decimal? TotalSpecialConsumeTaxAmountOc { get; set; }
        public decimal? TotalSpecialConsumeTaxAmount { get; set; }
        public decimal? TotalCustomBeforeAmount { get; set; }
        public int? DisplayOnBook { get; set; }
        public bool? IsPaid { get; set; }
        public bool? IsPostedCashBookFinance { get; set; }
        public bool? IsPostedCashBookManagement { get; set; }
        public DateTime? CashBookPostedDate { get; set; }
        public bool? IsPostedInventoryBookFinance { get; set; }
        public bool? IsPostedInventoryBookManagement { get; set; }
        public DateTime? InventoryPostedDate { get; set; }
        public int? RefOrder { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public string CustomField7 { get; set; }
        public string CustomField8 { get; set; }
        public string CustomField9 { get; set; }
        public string CustomField10 { get; set; }
        public int? Catype { get; set; }
        public string ListTableName { get; set; }
        public string RefTypeName { get; set; }
        public string CajournalMemo { get; set; }
        public decimal? CabaamountOc { get; set; }
        public decimal? Cabaamount { get; set; }
        public string InvNo { get; set; }
        public DateTime? InvDate { get; set; }
        public string InvSeries { get; set; }
        public DateTime? InrefOrder { get; set; }
    }
}
